site_name: MatrixOne Docs
repo_name: matrixorigin/matrixone
repo_url: https://github.com/matrixorigin/matrixone
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.instant  
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    scheme: mo
  font:
    text: Montserrat
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://www.matrixorigin.cn

nav:
  - MatrixOne:
    - Home: 
      - Introduction: MatrixOne/Home/Introduction.md
    - Develop:
      - Design a Database: MatrixOne/Develop/DesignADatabase.md
    - Deploy:
      - Software and Hardware Requirements: MatrixOne/Deploy/Software-and-Hardware-Requirements.md
    - FAQs:
      - MatrixOneFAQs: MatrixOne/FAQs/MatrixOne-FAQs.md
