site_name: MatrixOne Docs
repo_name: matrixorigin/matrixone
repo_url: https://github.com/matrixorigin/matrixone
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.instant  
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    scheme: mo
  font:
    text: Verdana
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://www.matrixorigin.cn

nav:
  - MatrixOne:
    - Home: Home/Introduction.md
    - Deploy: Deploy/Software-and-Hardware-Requirements.md
    - FAQs: FAQs/MatrixOne-FAQs.md
